### ISSUE TITLE
Embulk 0.9.23 raise multiple exception if v0.10 api use.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1409]
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: macOS 11.2.3
  * Java version: 1.8.251
  * Embulk version: build(0.10.26), run: 0.9.23
  * Your Embulk configuration: See below
  * Plugin versions: See below

```
https://github.com/hiroyuki-sato/embulk-parser-jsonpath
cd embulk-parser-jsonpath/
git checkout -b topic/try-v0_9-v0_10 origin/topic/try-v0_9-v0_10
./gradlew gem
```

## Expected behavior

```
embulk-10.0.27 run -I build/gemContents example/conf.yml
```

### Case1: with one input file

example/conf.yml

```yaml
in:
  type: file
  path_prefix: example/input2 # <-- Modifiy HERE
  parser:
    type: jsonpath
    root: "$.results"
    default_timezone: "Asia/Tokyo"
    columns:
      - { name: "name",          type: string }
      - { name: "city",          type: string }
      - { name: "street_name",   type: string }
      - { name: "zip_code",      type: string }
      - { name: "registered_at", type: timestamp, format: "%Y-%m-%d %H:%M:%S" }
      - { name: "vegetarian",    type: boolean }
      - { name: "age",           type: long }
      - { name: "ratio",         type: double }
out:
  type: stdout
```

```
embulk run -I build/gemContents/lib example/conf.yml
```

```
Error: java.lang.RuntimeException: java.lang.NoSuchMethodError: org.embulk.spi.Buffer: method <init>()V not found
```

### Case2: with trhee input files and "null" output

copy file

```
cp example/input2.json example/input3.json
```

```yaml
in:
  type: file
  path_prefix: example/input
  parser:
    type: jsonpath
    root: "$.results"
    default_timezone: "Asia/Tokyo"
    columns:
      - { name: "name",          type: string }
      - { name: "city",          type: string }
      - { name: "street_name",   type: string }
      - { name: "zip_code",      type: string }
      - { name: "registered_at", type: timestamp, format: "%Y-%m-%d %H:%M:%S" }
      - { name: "vegetarian",    type: boolean }
      - { name: "age",           type: long }
      - { name: "ratio",         type: double }
out:
  type: "null" # <-- MODIFY HERE stdout -> null
```

embulk run -I build/gemContents/lib example/conf.yml

```
Error: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class org.embulk.util.file.EmptyBuffer
```

### Case1:

```
embulk  run -I build/gemContents/lib example/conf.yml
2021-03-22 09:47:33.311 +0900: Embulk v0.9.23
2021-03-22 09:47:34.635 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2021-03-22 09:47:38.968 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/user/.embulk/lib/gems"
2021-03-22 09:47:40.982 +0900 [INFO] (main): Started Embulk v0.9.23
2021-03-22 09:47:41.210 +0900 [INFO] (0001:transaction): Loaded plugin embulk/parser/jsonpath from a load path
2021-03-22 09:47:41.284 +0900 [INFO] (0001:transaction): Listing local files at directory 'example' filtering filename by prefix 'input2'
2021-03-22 09:47:41.286 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2021-03-22 09:47:41.289 +0900 [INFO] (0001:transaction): Loading files [example/input2.json]
2021-03-22 09:47:41.409 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2021-03-22 09:47:41.432 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2021-03-22 09:47:41.502 +0900 [INFO] (0013:task-0000): JSONPath = $.results
2021-03-22 09:47:41.543 +0900 [WARN] (0013:task-0000): embulk-parser-jsonpath is expected to work with Embulk v0.10.17+.
java.lang.NoSuchMethodError: org.embulk.spi.Exec.getPageBuilder(Lorg/embulk/spi/BufferAllocator;Lorg/embulk/spi/Schema;Lorg/embulk/spi/PageOutput;)Lorg/embulk/spi/PageBuilder;
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.getPageBuilder(JsonpathParserPlugin.java:281) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:160) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230) [embulk:0.9.23]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251]
2021-03-22 09:47:41.605 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.lang.NoSuchMethodError: org.embulk.spi.Buffer: method <init>()V not found
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
        at org.embulk.cli.Main.main(Main.java:64)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: org.embulk.spi.Buffer: method <init>()V not found
        at org.embulk.exec.BulkLoader$LoaderState.getRepresentativeException(BulkLoader.java:285)
        at org.embulk.exec.BulkLoader.execute(BulkLoader.java:684)
        at org.embulk.exec.BulkLoader.access$300(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$4$1$1$1.run(BulkLoader.java:528)
        at org.embulk.standards.StdoutOutputPlugin.resume(StdoutOutputPlugin.java:64)
        at org.embulk.standards.StdoutOutputPlugin.transaction(StdoutOutputPlugin.java:57)
        at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:521)
        at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:50)
        at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:516)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
        at org.embulk.spi.util.Filters.transaction(Filters.java:42)
        at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:511)
        at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:112)
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.transaction(JsonpathParserPlugin.java:141)
        at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:107)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
        at org.embulk.spi.util.Decoders.transaction(Decoders.java:29)
        at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:105)
        at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:79)
        at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:72)
        at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
        ... 11 more
Caused by: java.lang.NoSuchMethodError: org.embulk.spi.Buffer: method <init>()V not found
        at org.embulk.util.file.EmptyBuffer.<init>(EmptyBuffer.java:22)
        at org.embulk.util.file.EmptyBuffer.<clinit>(EmptyBuffer.java:81)
        at org.embulk.util.file.FileInputInputStream.<init>(FileInputInputStream.java:26)
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:163)
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Error: java.lang.RuntimeException: java.lang.NoSuchMethodError: org.embulk.spi.Buffer: method <init>()V not found
```

### Case2:

```
embulk  run -I build/gemContents/lib example/conf.yml
2021-03-22 09:46:17.091 +0900: Embulk v0.9.23
2021-03-22 09:46:18.469 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2021-03-22 09:46:22.588 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/user/.embulk/lib/gems"
2021-03-22 09:46:24.360 +0900 [INFO] (main): Started Embulk v0.9.23
2021-03-22 09:46:24.591 +0900 [INFO] (0001:transaction): Loaded plugin embulk/parser/jsonpath from a load path
2021-03-22 09:46:24.668 +0900 [INFO] (0001:transaction): Listing local files at directory 'example' filtering filename by prefix 'input'
2021-03-22 09:46:24.669 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2021-03-22 09:46:24.672 +0900 [INFO] (0001:transaction): Loading files [example/input.json, example/input3.json, example/input2.json]
2021-03-22 09:46:24.793 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 6 = input tasks 3 * 2
2021-03-22 09:46:24.803 +0900 [INFO] (0001:transaction): {done:  0 / 3, running: 0}
2021-03-22 09:46:24.867 +0900 [INFO] (0014:task-0001): JSONPath = $.results
2021-03-22 09:46:24.867 +0900 [INFO] (0013:task-0000): JSONPath = $.results
2021-03-22 09:46:24.873 +0900 [INFO] (0015:task-0002): JSONPath = $.results
2021-03-22 09:46:24.914 +0900 [WARN] (0013:task-0000): embulk-parser-jsonpath is expected to work with Embulk v0.10.17+.
java.lang.NoSuchMethodError: org.embulk.spi.Exec.getPageBuilder(Lorg/embulk/spi/BufferAllocator;Lorg/embulk/spi/Schema;Lorg/embulk/spi/PageOutput;)Lorg/embulk/spi/PageBuilder;
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.getPageBuilder(JsonpathParserPlugin.java:281) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:160) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230) [embulk:0.9.23]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251]
2021-03-22 09:46:24.914 +0900 [WARN] (0015:task-0002): embulk-parser-jsonpath is expected to work with Embulk v0.10.17+.
java.lang.NoSuchMethodError: org.embulk.spi.Exec.getPageBuilder(Lorg/embulk/spi/BufferAllocator;Lorg/embulk/spi/Schema;Lorg/embulk/spi/PageOutput;)Lorg/embulk/spi/PageBuilder;
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.getPageBuilder(JsonpathParserPlugin.java:281) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:160) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230) [embulk:0.9.23]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251]
2021-03-22 09:46:24.915 +0900 [WARN] (0014:task-0001): embulk-parser-jsonpath is expected to work with Embulk v0.10.17+.
java.lang.NoSuchMethodError: org.embulk.spi.Exec.getPageBuilder(Lorg/embulk/spi/BufferAllocator;Lorg/embulk/spi/Schema;Lorg/embulk/spi/PageOutput;)Lorg/embulk/spi/PageBuilder;
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.getPageBuilder(JsonpathParserPlugin.java:281) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:160) [embulk-parser-jsonpath-0.3.2.jar:0.3.2]
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233) [embulk:0.9.23]
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230) [embulk:0.9.23]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251]
2021-03-22 09:46:24.990 +0900 [INFO] (0001:transaction): {done:  3 / 3, running: 0}
2021-03-22 09:46:24.990 +0900 [INFO] (0001:transaction): {done:  3 / 3, running: 0}
2021-03-22 09:46:24.991 +0900 [INFO] (0001:transaction): {done:  3 / 3, running: 0}
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class org.embulk.util.file.EmptyBuffer
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
        at org.embulk.cli.Main.main(Main.java:64)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class org.embulk.util.file.EmptyBuffer
        at org.embulk.exec.BulkLoader$LoaderState.getRepresentativeException(BulkLoader.java:285)
        at org.embulk.exec.BulkLoader.execute(BulkLoader.java:684)
        at org.embulk.exec.BulkLoader.access$300(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$4$1$1$1.run(BulkLoader.java:528)
        at org.embulk.standards.NullOutputPlugin.resume(NullOutputPlugin.java:25)
        at org.embulk.standards.NullOutputPlugin.transaction(NullOutputPlugin.java:19)
        at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:521)
        at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:50)
        at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:516)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
        at org.embulk.spi.util.Filters.transaction(Filters.java:42)
        at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:511)
        at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:112)
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.transaction(JsonpathParserPlugin.java:141)
        at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:107)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
        at org.embulk.spi.util.Decoders.transaction(Decoders.java:29)
        at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:105)
        at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:79)
        at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:72)
        at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
        ... 11 more
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.embulk.util.file.EmptyBuffer
                at org.embulk.util.file.FileInputInputStream.<init>(FileInputInputStream.java:26)
                at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:163)
                at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.NoSuchMethodError: org.embulk.spi.Buffer: method <init>()V not found
                at org.embulk.util.file.EmptyBuffer.<init>(EmptyBuffer.java:22)
                at org.embulk.util.file.EmptyBuffer.<clinit>(EmptyBuffer.java:81)
                at org.embulk.util.file.FileInputInputStream.<init>(FileInputInputStream.java:26)
                at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:163)
                at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.embulk.util.file.EmptyBuffer
        at org.embulk.util.file.FileInputInputStream.<init>(FileInputInputStream.java:26)
        at org.embulk.parser.jsonpath.JsonpathParserPlugin.run(JsonpathParserPlugin.java:163)
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Error: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class org.embulk.util.file.EmptyBuffer
```

**Comment by dmikurube** [comment]
Should be fixed by #1410 in v0.10.28.

**Comment by dmikurube** [comment]
Ah, no, not fixed yet until `embulk-util-file`'s fixed.

**Comment by dmikurube** [comment]
@hiroyuki-sato Released `embulk-util-file:0.1.2`. (It may take ~30 min to be ready on Maven Central.)

Please try rebuliding your `embulk-parser-jsonpath` with the updated version.

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank  for fixing the issue. I rebuilt `embulk-parser-jsonpath` using `embulk-util-file:0.1.2`. It worked fine with Embulk 0.9.23
